---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data analyst with strong academic background in sociology and statistics and high programming command built while I was a student at the university and a data scientist in the private sector. Looking forward to proceeding myself in the field of data visualization and communication.

Working at Deloitte, HPE and Illuminati Lab I have carried out customer segmentations, predictions of indicators and visualizations/interpretations of results.

My latest statistical research is data visualization in geographical maps: as an example, I have elaborated this [map](http://ec2-18-217-50-244.us-east-2.compute.amazonaws.com:3838/myapp/) with the results and the abstention by districts of the last municipal elections of Barcelona. If you want to know more about me, you can read [my master's thesis](https://upcommons.upc.edu/bitstream/handle/2117/88463/memoria.pdf?sequence=1&amp;isAllowed=y), where I automatically synthesize in 20 subjects the speeches of the Parliament of the 9th and 10th legislatures and visualize them in an [interactive graphic](https://marta-elias.shinyapps.io/shinnyapp/#topic=12&amp;lambda=0.5&amp;term=).

If you want to read my personal CV, click over [here](https://docs.google.com/viewer?url=https://github.com/martaelias/aboutme/raw/master/EnglishCV.pdf)

To contact me, you can find me on [LinkedIn](https://www.linkedin.com/in/martaeliasmoreno/) or send me an email to ‘meliasmoreno@gmail.com'.
