---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Estadista i sociòloga amb tres anys d’experiència en l'àmbit de l’anàlisi de dades, tant en consultoria com en investigació acadèmica. Amb ganes de seguir aprenent i aquest cop d’especialitzar-se en el món de la visualització de dades i la comunicació.

La meva última incursió estadística ha estat la visualització de dades en mapes geogràfics: a tall d’exemple, he elaborat aquest [mapa](http://ec2-18-217-50-244.us-east-2.compute.amazonaws.com:3838/myapp/) amb els resultats i l'abstenció per barris de les darreres eleccions municipals de Barcelona. Si t'ha pica la curiositat, també pots fer el xafarder al meu [treball de final de màster](https://upcommons.upc.edu/bitstream/handle/2117/88463/memoria.pdf?sequence=1&isAllowed=y), on vaig intentar sintetitzar de manera automàtica els discursos del Parlament de les passades legislatures en una [visualització](https://marta-elias.shinyapps.io/shinnyapp/#topic=12&lambda=0.5&term=).

Si vols llegir el meu CV personal, el pots trobar clicant [aquí](https://docs.google.com/viewer?url=https://github.com/martaelias/aboutme/raw/master/CV.pdf). Si vols contactar amb mi, pots fer-ho des del [LinkedIn](https://www.linkedin.com/in/martaeliasmoreno/) o bé per correu electrònic escrivint a 'meliasmoreno@gmail.com'